# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [5]:
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [6]:
arr = vector.shape
print(arr)

(39,)


5. Print the type of the previous array in question 3

In [9]:
print(type(vector))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamir/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamir/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamir/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamir/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamir/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamir/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamir/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamir/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [12]:
print(len(vector))

39


8. Create a boolean array with all the True values

In [13]:
x=np.ones((2, 2), dtype=bool)
print(x)

[[ True  True]
 [ True  True]]


9. Create a two dimensional array




In [14]:
array = np.arange(20).reshape(4,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


10. Create a three dimensional array



In [15]:
array = np.arange(27).reshape(3,3,3)
print(array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
reverse = vector[::-1]
print(reverse)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [19]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11: ")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11: 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [21]:
array=np.identity(3)
print('3x3 matrix:')
print(array)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [25]:
arr = np.array([1, 2, 3, 4, 5])
print("Old Array:", arr)
arr = arr.astype('float64')
print("New Array: ", arr)

Old Array: [1 2 3 4 5]
New Array:  [1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [27]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
mul = np.multiply(arr1, arr2)
print(mul)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [29]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

Com = arr1 == arr2
result = Com.all()
print(result)

False


17. Extract all odd numbers from arr with values(0-9)

In [36]:
a = np.array([1,2,3,4,5,6,7,8,9])
x=a[a % 2 == 1]
print(x)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]= -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [45]:
arr = np.arange(10)
print("Old Array: ",arr)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
print("New Array: ", arr)

Old Array:  [0 1 2 3 4 5 6 7 8 9]
New Array:  [ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [46]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [50]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [54]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:]=12
print(arr3d)

[[[12 12 12]
  [12 12 12]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [70]:
array1 = np.arange(0,9).reshape(3,3)
print(array1)
array= array1[:1, 1:3]
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [72]:
array1 = np.arange(0,9).reshape(3,3)
print(array1)
array= array1[1:2, 1:2]
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [78]:
array1 = np.arange(0,9).reshape(3,3)
print(array1)
array= array1[:2, 2:3]
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [80]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum Value: ", xmin)
print("Maximum Value: ", xmax)

Original Array:
[[0.69207707 0.64807245 0.58634814 0.98791739 0.63581543 0.12638257
  0.69458906 0.47982958 0.32410255 0.34923193]
 [0.00593561 0.85133584 0.0519457  0.31905243 0.31035109 0.43102551
  0.75749627 0.05788019 0.80321952 0.99708398]
 [0.84425784 0.55663475 0.5368697  0.18792249 0.77507977 0.37780983
  0.25493843 0.38252068 0.98494961 0.48911877]
 [0.39743012 0.41633004 0.96838397 0.16264423 0.58064325 0.90700162
  0.68517329 0.14970077 0.37692231 0.86172898]
 [0.01059035 0.5200076  0.93250062 0.36000372 0.61088142 0.37907271
  0.38733414 0.96991439 0.17289788 0.29547278]
 [0.75165794 0.28863689 0.04925074 0.00335952 0.85876034 0.22837075
  0.53623695 0.1248717  0.58454914 0.57298751]
 [0.91914071 0.73328584 0.30419391 0.66319963 0.44516961 0.78193384
  0.56102177 0.02701871 0.17043491 0.52618753]
 [0.68369296 0.13177918 0.11858202 0.76677624 0.76457765 0.17850902
  0.54302999 0.32886165 0.52537664 0.70353648]
 [0.28401004 0.26656894 0.14851842 0.16228822 0.37896887 0.73183

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [83]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.intersect1d(a,b)))

(array([0, 1]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x = data[names != 'Will']
print(x)

[[-0.88054452 -0.38649768 -0.43031775 -1.34718505]
 [-0.9793902   1.45772939 -0.40643082 -0.29468735]
 [ 1.45317318  1.1180099  -0.76709873  1.28932674]
 [ 1.27665757  0.28549709  0.45054319 -0.37303444]
 [-2.08380796 -0.57254176 -2.53375539  1.16163955]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [87]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x = data[names != 'Will']
y = data[names != 'Joe']

print(x,y)

[[ 0.82215006 -0.37785584  1.01005845 -1.33965044]
 [ 1.37412766 -0.48884316  0.1281426   0.81565211]
 [-0.03159308  0.40924828  0.03147033 -0.63121405]
 [ 0.93040577 -1.2638055  -0.58744975  0.45057016]
 [-0.60964383 -0.74984344 -0.53829187  1.14646948]] [[ 0.82215006 -0.37785584  1.01005845 -1.33965044]
 [ 1.53699765 -0.47200521  0.81891094  0.58677824]
 [-0.03159308  0.40924828  0.03147033 -0.63121405]
 [-0.24416989  1.77369835 -0.32489343  0.76710182]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [91]:
array = np.arange(0,15).reshape(5,3)
print(array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [92]:
array = np.arange(0,16).reshape(2,2,4)
print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


33. Swap axes of the array you created in Question 32

In [93]:
array = np.arange(0,16).reshape(2,2,4)
swap = array.T
print(swap)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [95]:
array = np.arange(10)
array = np.sqrt(array)
x = np.where(array<0.5,0,array)
print(x)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [110]:
arr1 = np.random.random(12)
arr2  =np.random.random(12)

arr3 = np.max((arr1, arr2))
print(arr3)


0.9938571476313005


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [96]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
_, idx = np.unique(names, return_index=True)
print(names[np.sort(idx)])

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [97]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [101]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)

[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [102]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [104]:
array = np.random.random(20)
Sum = np.cumsum(array)
print(Sum)

[ 0.4450024   1.38043476  1.38150822  2.28250064  3.27016647  4.12843412
  4.5573119   5.06445255  5.95143657  6.24510633  6.86191082  7.31532019
  7.5000124   7.70236387  8.58738359  9.15101473 10.0430645  10.54036667
 11.22205116 12.04933719]
