# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]

c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("initial array", str(array1)) 
result = array1.flatten()
print("New resulting array: ", result) 

initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array:  [1 2 3 2 4 5 1 2 3]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [1]:
import numpy as np
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
z = x.flatten()
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
x = np.random.random((5,5))
z = np.square(x)
print(z)

[[2.39183567e-01 2.13821691e-01 8.02769796e-04 9.00907989e-01
  1.17991877e-01]
 [8.98690295e-01 1.94695156e-01 6.23833160e-01 7.03429727e-02
  1.51636662e-02]
 [3.95944265e-01 4.69144639e-02 7.08771577e-02 8.17512466e-01
  1.92640572e-02]
 [5.28071287e-01 1.94929626e-01 7.27703141e-01 1.04306993e-03
  6.98298343e-02]
 [8.81823104e-02 4.28201731e-01 1.46457841e-01 7.66201904e-01
  3.91014558e-02]]


In [ ]:
## Question:8

### Create 5x6 an array and find the mean?

In [29]:
x = np.random.random((5,6))
print(x)
z = np.mean(x)
print("Mean of the X: ",z)

[[0.67096159 0.37688721 0.25013474 0.52323321 0.67418346 0.6574508 ]
 [0.76605835 0.88926543 0.82922167 0.35016825 0.0953944  0.03106649]
 [0.1711169  0.69925847 0.71692407 0.69438961 0.25940818 0.97995457]
 [0.60965429 0.0403781  0.81335523 0.38994873 0.29112763 0.15617894]
 [0.06729421 0.78281833 0.20009794 0.64417782 0.4199872  0.5335413 ]]
Mean of the X:  0.48612123715583233


## Question:9

### Find the standard deviation of the previous array in Q8?

In [2]:
x = np.random.random((5,6))

z = np.std(x, dtype = np.float32)

print("Deviation of array: ", z)

Deviation of array:  0.286338


## Question:10

### Find the median of the previous array in Q8?

In [13]:
x = np.random.random((5,6))
z = np.median(x)
print("Median of An array: ", z)

Median of An array:  0.43238845859288016


## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
x = np.array([[0, 1, 2],
       [3, 4, 5]])
z = np.transpose(x)
print(z)

[[0 3]
 [1 4]
 [2 5]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]]) 
print("4X4 array: ")
print(n_array)

Sum = np.trace(n_array)
print("Sum of the array: ", Sum)

4X4 array: 
[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
Sum of the array:  196


## Question:13

### Find the determinant of the previous array in Q12?

In [20]:
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]])
determinant =np.linalg.det(n_array)
print("Determinant of the Array: ", determinant)

Determinant of the Array:  -25166735.999999996


## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]])
percentile_5th = np.percentile(n_array, 5)
print("5th percentile of array: ",percentile_5th)
percentile_95th = np.percentile(n_array, 95)
print("95th percentile of array: ",percentile_95th)

5th percentile of array:  3.5
95th percentile of array:  110.75


## Question:15

### How to find if a given array has any null values?

In [4]:
print("Original array:")
nums = np.random.randint(0,3,(4,10))
print(nums)
print("\nTest whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())


Original array:
[[0 0 1 2 1 2 0 0 2 0]
 [1 2 0 1 0 1 1 1 0 1]
 [0 1 1 2 2 2 2 0 1 2]
 [1 0 0 0 1 2 0 1 2 2]]

Test whether the said array has null columns or not:
False
